### ISSUE TITLE
Partition configuration is ineffective in Python interface

### ISSUE THREAD

**Issue by leonfg** [ADLINK-IST/opensplice#151]
Opensplice community 6.9.181127OSS.
In my [project](https://github.com/leonfg/InteropDDS) I set [pub](https://github.com/leonfg/InteropDDS/blob/master/pub.py) and [sub](https://github.com/leonfg/InteropDDS/blob/master/sub.py) in different partition names in [XML](https://github.com/leonfg/InteropDDS/blob/master/TestQoS.xml) and they can still communicate with each other.
Furthermore, [subhello.py](https://github.com/leonfg/InteropDDS/blob/master/subhello.py) can receive data from [sacpp_helloworld_pub.exe](https://github.com/ADLINK-IST/opensplice/tree/master/examples/dcps/HelloWorld/cpp) if I comment the partition name specification in cpp code. But setting same partition name with cpp in XML will not work.

**Comment by vivekpandey02** [comment]
Dear Fire God,
In your Pub and Sub, partition name is not set correctly (you have missed `<element></element>` tag under name), hence, it uses default partition. Since both pub and sub are using default partition your sub application gets the data published by your pub application. 

To set partition name in your QoS_Profile.xml file, you must follow the following syntex:
```
<publisher_qos>
    <partition>
        <name>
            <element>HelloWorld Partition</element>
        </name>
    </partition>
</publisher_qos>
```

For multi partition, Your Partition Qos in XML looks like:
```
<publisher_qos>
    <partition>
        <name>
            <element>Partition1</element>
            <element>Partition2</element>
        </name>
    </partition>
</publisher_qos>
```

For more details how to set different QoS in XML file, you can go through  link below:
http://download.prismtech.com/docs/Vortex/html/ospl/PythonDCPSAPIGuide/qos_provider.html#qos-provider

With best regards,
Vivek Kumar Pandey
Solutions Architect
ADLINK Technology

**Comment by leonfg** [comment]
Thank you very much!
