### ISSUE TITLE
Process left hanging when using "FreeLibrary" on window

### ISSUE THREAD

**Issue by TBRTechSAT** [ADLINK-IST/opensplice#56]
The following program hangs on Windows. Freeing the library seems to result in a deadlock.
Since version 6.7.

```
#include <Windows.h>

int main(int argc, char** argv)
{
    HINSTANCE var_library = LoadLibrary("ddskernel.dll");
    if (var_library == NULL) {
        exit(1);
    }

    Sleep(1000);

    FreeLibrary(var_library);

    return 0;
}
```

**Comment by ernstvanveenendaal** [comment]
Hi,

This is indeed an issue in our product, we're indirectly calling some thread synchronization functions from the DllMain function, which causes the deadlock. 

It is, however, not common to load (and free) our library using the LoadLibrary manually, as normally creating a domain participant would initialize everything needed to use OpenSplice. Is there a specific use-case to use this?

Regards,
Ernst

**Comment by TBRTechSAT** [comment]
Thanks for your reply.

To give you a little bit a context, we are developing a communication standard based on the DDS protocol for an R&T project. The project is called Virtual Hybrid Testing Next Generation (VHTNG) and aims at standardizing test bench equipment interconnection. This project is driven by AIRBUS and regroups more than fifteen different companies in France and Germany.

We develop a reference implementation of this communication standard. This implementation is open source (under the EUPL license) and based on OpenSplice Community Edition.

The partners involved in the project have different ways to integrate this reference implementation in their systems. Some of them perform a dynamic load (and unload) of the library and this process cannot be modified on their side.

Regards,

Thibault

**Comment by PatrickM-adlink** [comment]
It hangs on the signal-handler thread-join. 

The issue is that `DllMain()` is executed twice by the same thread: once to detach the process and another time to detach the signal-handler thread (which is started by `DllMain()` when the process attached). Windows protects access to `DllMain()` so it's a classical deadlock. More details here: https://blogs.msdn.microsoft.com/oldnewthing/20070904-00/?p=25283

A valid workaround is to call `os_osExit()` before calling `FreeLibrary()`, however  to keep a valid ref-count, one should also call `os_osInit()` directly after `LoadLibrary()` (if not, an error is printed in release builds but in a dev build it asserts).

@TBRTechSAT I noticed it's been a while since you opened this issue. Are you still affected, does this workaround fit with you usecase?

**Comment by brezillon** [comment]
Hi,

Thanks for your answer. 
I understand the issue and can live with the workaround but am wondering if a fix shouldn't be provided in a future release of OpenSplice anyway.
Our current workaround has been to switch to the RTI-Connext DDS Implementation.

Best regards,

Thibault
