### ISSUE TITLE
Vast majority of messages lost when analysing core of opensplice

### ISSUE THREAD

**Issue by od42** [ADLINK-IST/opensplice#65]
Hello,

our research group is trying to locate or prove the lack of concurrency-related bugs in opensplice DDS using dynamic analysis. Our goal is to try out our analysis tools and to help ensuring and/or improving the quality of opensplice DDS.

Unfortunately, the real-time nature of opensplice DDS does not combine well with the significant overhead of our dynamic analysis tool. Namely, we had to bypass several time-outs by altering the source code of opensplice DDS. Note that we are not aiming at checking any real-time properties, we are aiming at pure concurrency bugs (data races, deadlocks, etc.), and so the alteration of the time-outs should be acceptable for us.

We managed to get to a point where we can analyse a full run of the Message Board tutorial example program with no errors. However, a significant number of messages is somehow lost and not delivered. We were not able to find the cause of this behaviour.

Would somebody point us to the points of opensplice which could cause the loss of messages? Or to the settings of opensplice which should modify the behaviour not to discard the messages?

Best regards,
Ondřej Vašíček
(VeriFIT research group, Brno University of Technology, http://www.fit.vutbr.cz/research/groups/verifit/ )

**Comment by michielb-adlink** [comment]
Hello Ondřej,

I like to help you to find out why the program is not behaving as expected. For this I do need a bit more information, can you start by sending me the output of the executables you are using and tell me what examples you're expecting but are missing?

- Michiel

**Comment by od42** [comment]
Hello Michiel,

The issue is best observable on the Tutorial example. In two separate terminals I launch MessageBoard and Chatter with no parameters.

Output with no analysis looks like this:
- Chatter
```
Writing message: "Hi There, I will send you 10 more messages."
Writing message: "Message no. 1"
Writing message: "Message no. 2"
Writing message: "Message no. 3"
Writing message: "Message no. 4"
Writing message: "Message no. 5"
Writing message: "Message no. 6"
Writing message: "Message no. 7"
Writing message: "Message no. 8"
Writing message: "Message no. 9"
Writing message: "Message no. 10"
Completed Chatter example.
```
- MessageBoard
```
MessageBoard has opened: send a ChatMessage with userID = -1 to close it....

Chatter 1: Hi There, I will send you 10 more messages.
Chatter 1: Message no. 1
Chatter 1: Message no. 2
Chatter 1: Message no. 3
Chatter 1: Message no. 4
Chatter 1: Message no. 5
Chatter 1: Message no. 6
Chatter 1: Message no. 7
Chatter 1: Message no. 8
Chatter 1: Message no. 9
Chatter 1: Message no. 10
```

Output is the same when MessageBoard is being analysed.
But when Chatter is being analysed the output looks like this:
- Chatter - same as before
```
Writing message: "Hi There, I will send you 10 more messages."
Writing message: "Message no. 1"
Writing message: "Message no. 2"
Writing message: "Message no. 3"
Writing message: "Message no. 4"
Writing message: "Message no. 5"
Writing message: "Message no. 6"
Writing message: "Message no. 7"
Writing message: "Message no. 8"
Writing message: "Message no. 9"
Writing message: "Message no. 10"
Completed Chatter example.
```
- MessageBoard - messages 1-6 lost
```
MessageBoard has opened: send a ChatMessage with userID = -1 to close it....

Name not found!! id = 1: Message no. 7
Name not found!! id = 1: Message no. 8
Name not found!! id = 1: Message no. 9
Name not found!! id = 1: Message no. 10
```
Note that the number of messages scales with the overhead of our analysis (slower analyser means more messages lost).

I have tried changing the dds xml conf file using osplconf in various ways with no luck.
I can also provide any details of the changes I have made to opensplice dds, if needed.

Ondřej Vašíček

**Comment by michielb-adlink** [comment]
I'm writing this under the assumption that the analyzer you're using significantly slows down the process being analyzed. For this and the other examples we have created we assume that both processes are of the same speed and the subscriber is started before the publisher. In this case that means starting the messageBoard before the Chatter, but think you're doing this in the correct order.

What I think is that the Chatter application is slowed down in such a manner that it starts publishing its data before the ddsi network service is operational and the readers on the other side are discovered. Because we assume equality in processes we have not included any synchronisation between the two. A way to improve upon the example is to change the QoS setting of both the messageBoard and Chatter application for both the "Chat_NameService" and "Chat_NamedMessage" topic to reliable and transient-local. This should ensure less missed samples. However this will not completely make up for the missed samples as this is partly expected behavior as the writer publishes the samples in the same instance with a history depth of 1. So when the sample can't be delivered it is kept in the writer history any following written sample for the same instance overwrites the previous one.

Another way to improve upon the example could be to add synchronisation between the two processes, could probable be one sided as the Chatter is the one analyzed and slowed, is to have it match on publication by using the DDS_DataWriter_get_publication_matched_status function or a listener (DDS_DataWriterListener_PublicationMatchedListener). This then needs to be added after the writers have been created in the Chatter application and before the first sample is written. A simpler but not so correct solution could also be to add a sleep of about 10 seconds to ensure discovery and startup are complete before writing.

**Comment by od42** [comment]
Thank you very much!

That really was the issue. I tested it out by inserting the sleep you suggested as a temporary quick fix. All messages are now delivered correctly even for our slowest analyser (a sleep of over 10mins is needed).

I will make sure to let you know, if our analysis produces any interesting results.

Best regards,
Ondřej Vašíček
