### ISSUE TITLE
Operation of the durability service in the local network.

### ISSUE THREAD

**Issue by WOLFY888** [ADLINK-IST/opensplice#73]
The problem is this: there are 2 machines connected to the local network: the A-machine and the B-machine. On an A-machine, the writer publishes the data and shuts down. After a while the B-machine starts reader and he does not receive these data. Experimentally, it was found out that the reader on the B-machine receives historical data only when the A-machine is also running the reader who received this data (it can be run while the writer is working or after the writer has completed the work, there is no difference).
All quality policies of readers correspond to the quality policies of the topic and the writer, the time on both machines is synchronized, all data is persistent. I attach the contents of the configuration file ospl.xml
![ospl](https://user-images.githubusercontent.com/44889553/48930932-97c55600-ef04-11e8-9600-ffe15ebcf99e.jpg)

**Comment by hansvanthag** [comment]
In order to obtain historical data from a durability service, there should at least be one of those durability-services (kept) running in the system.

In our commercially-supported OpenSplice version we support 'federated deployment' that allows to start the services independent from applications on a specific node (where shared-memory is used to within that node to give the services access to the application's data). So in that case its sufficient to start-up one or more federations somewhere that will retain historical data (independently from the coming/going of applications)

Our community-version however doesn't include this federated-deployment mode implying that you have to run a/any application yourself that has a durability-service configured (via its configuration).

So in your case that was the reader-application that you kept running experimentally. Note that its only required to create a domainParticipant for the correct DDS-domain in that '_durability-application'_ as all the work will be done by its configured durability service'. It also doesn't matter on which node that durability-application is running as long as its there when the data gets published and is still around when somewhere/sometimes-else a late-joining application is started.

Finally, you could start multiple of such '_durability-applications_' in your system to achieve redundancy (as the durability-services will keep each other 'aligned').

Hope this helps,
Regards,
Hans

**Comment by WOLFY888** [comment]
@hansvanthag Thank you! I assumed that there must be a fictitious reader. But it turns out that only a domain participant is enough
